# Generated by Django 5.1.4 on 2025-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_word_alter_game_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for second player'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('paused', 'Paused')], default='waiting', max_length=20),
        ),
    ]
