# Generated by Django 5.1.4 on 2025-05-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_game_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
