# Generated by Django 5.1.4 on 2025-05-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game_player1_score_game_player2_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='wrong_guesses',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished'), ('paused', 'Paused')], default='waiting', max_length=20),
        ),
    ]
