# Generated by Django 5.1.4 on 2025-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_game_wrong_guesses_alter_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_score',
            field=models.IntegerField(default=0),
        ),
    ]
